window.WC_DATA = {
  meta: {
    tournament: "FIFA World Cup 2026",
    updatedAt: "2026-05-24",
    timezoneBase: "ET",
    timezoneUser: "Europe/Rome",
  },
  sources: [
    {
      label: "FIFA calendario ufficiale",
      url: "https://www.fifa.com/en/tournaments/mens/worldcup/canadamexicousa2026/articles/match-schedule-fixtures-results-teams-stadiums",
    },
    {
      label: "FIFA ranking ufficiale 1 aprile 2026",
      url: "https://vod.fifa.com/fifa-world-ranking/men/news/france-1st-fifa-coca-cola-world-ranking-april-2026",
    },
    {
      label: "DIRECTV calendario con orari ET",
      url: "https://www.directv.com/insider/world-cup-schedule/",
    },
    {
      label: "ESPN riepilogo ranking FIFA top 50",
      url: "https://www.espn.com/soccer/story/_/id/46664763/fifa-mens-top-50-world-rankings",
    },
    {
      label: "FIFA regole convocati 2026",
      url: "https://www.fifa.com/en/tournaments/mens/worldcup/canadamexicousa2026/articles/squad-lists-number-date",
    },
  ],
  dailyNews: [
    {
      id: "germany-squad-neuer",
      date: "2026-05-21",
      priority: 3,
      label: "NEWS",
      badge: "Aggiornamento",
      tag: "Germania",
      title: "Neuer torna in nazionale: Nagelsmann lo include nella lista mondiale",
      summary:
        "Manuel Neuer rientra nella rosa della Germania per il Mondiale 2026. Il Girone E diventa subito piu interessante: debutto contro Curacao, poi Costa d'Avorio ed Ecuador.",
      image: "https://commons.wikimedia.org/wiki/Special:FilePath/Manuel_Peter_Neuer_2018.jpg?width=760",
      imageAlt: "Manuel Neuer con la Germania",
      source: "FIFA",
      url: "https://www.fifa.com/en/tournaments/mens/worldcup/canadamexicousa2026/articles/germany-squad-neuer-nagelsmann-named",
    },
    {
      id: "squad-rules-release-period",
      date: "2026-05-21",
      priority: 2,
      label: "Notizia del giorno",
      badge: "Aggiornamento",
      tag: "Convocati",
      title: "Liste Mondiali: rose da 26 e rilascio giocatori dal 25 maggio",
      summary:
        "La preparazione entra nella fase chiave: ogni nazionale potra portare 26 calciatori e il periodo FIFA di rilascio iniziera il 25 maggio, con eccezioni per finali continentali fino al 30 maggio.",
      logoText: "FIFA",
      logoSub: "World Cup",
      source: "FIFA",
      url: "https://www.fifa.com/en/tournaments/mens/worldcup/canadamexicousa2026/articles/squad-lists-number-date",
    },
    {
      id: "switzerland-squad",
      date: "2026-05-20",
      label: "Aggiornamento",
      badge: "Aggiornamento",
      tag: "Girone B",
      title: "La Svizzera ha annunciato i 26 convocati per il Mondiale",
      summary:
        "La squadra di Murat Yakin entra nella fase finale con la lista ufficiale per Canada, Messico e Stati Uniti 2026.",
      image: "https://flagcdn.com/w640/ch.png",
      imageAlt: "Bandiera della Svizzera",
      source: "FIFA",
      url: "https://www.fifa.com/en/tournaments/mens/worldcup/canadamexicousa2026/articles/switzerland-squad-announcement-murat-yakin",
    },
    {
      id: "brazil-squad",
      date: "2026-05-18",
      label: "Aggiornamento",
      badge: "Aggiornamento",
      tag: "Girone C",
      title: "Brasile: Ancelotti sceglie Neymar nella lista dei 26",
      summary:
        "Il Brasile ha pubblicato la rosa mondiale con Neymar tra i nomi principali, mentre il modello FootballIQ tiene alta l'attenzione sul debutto contro il Marocco.",
      image: "assets/players/neymar-brazil-10.jpg",
      imageAlt: "Neymar con la maglia numero 10 del Brasile",
      source: "FIFA",
      url: "https://www.fifa.com/en/tournaments/mens/worldcup/canadamexicousa2026/articles/brazil-squad-announcement-carlo-ancelotti",
    },
  ],
  playerProfiles: {
    messi: {
      id: "messi",
      teamId: "arg",
      shortName: "Lionel Messi",
      fullName: "Lionel Andrés Messi",
      birthDate: "1987-06-24",
      height: "1,70 m",
      weight: "Dato non disponibile",
      nationality: "Argentina",
      club: "Inter Miami CF",
      role: "Attaccante",
      preferredFoot: "Sinistro",
      image: "https://commons.wikimedia.org/wiki/Special:FilePath/Lionel-Messi-Argentina-2022-FIFA-World-Cup.jpg?width=820",
      imageAlt: "Lionel Messi con la maglia dell'Argentina",
    },
    neymar: {
      id: "neymar",
      teamId: "bra",
      shortName: "Neymar",
      fullName: "Neymar da Silva Santos Júnior",
      birthDate: "1992-02-05",
      height: "1,75 m",
      weight: "Dato non disponibile",
      nationality: "Brasile",
      club: "Santos FC",
      role: "Trequartista",
      preferredFoot: "Destro",
      image: "assets/players/neymar-brazil-10.jpg",
      imageAlt: "Neymar con la maglia numero 10 del Brasile",
    },
    ronaldo: {
      id: "ronaldo",
      teamId: "por",
      shortName: "Cristiano Ronaldo",
      fullName: "Cristiano Ronaldo dos Santos Aveiro",
      birthDate: "1985-02-05",
      height: "1,85 m",
      weight: "80 kg",
      nationality: "Portogallo",
      club: "Al Nassr FC",
      role: "Attaccante",
      preferredFoot: "Dato non disponibile",
      image: "https://commons.wikimedia.org/wiki/Special:FilePath/Cristiano_Ronaldo_2018.jpg?width=760",
      imageAlt: "Cristiano Ronaldo con il Portogallo",
    },
    mbappe: {
      id: "mbappe",
      teamId: "fra",
      shortName: "Kylian Mbappe",
      aliases: ["Kylian Mbappé"],
      fullName: "Kylian Mbappé Lottin",
      birthDate: "1998-12-20",
      height: "1,78 m",
      weight: "75 kg",
      nationality: "Francia",
      club: "Real Madrid CF",
      role: "Attaccante",
      preferredFoot: "Destro",
      image: "https://commons.wikimedia.org/wiki/Special:FilePath/Kylian_Mbapp%C3%A9_2018.jpg?width=820",
      imageAlt: "Kylian Mbappe con la Francia",
    },
    maignan: {
      id: "maignan",
      teamId: "fra",
      aliases: ["Mike Maignan"],
      shortName: "Mike Maignan",
      fullName: "Mike Peterson Maignan",
      birthDate: "1995-07-03",
      height: "1,91 m",
      weight: "89 kg",
      nationality: "Francia",
      club: "AC Milan",
      role: "Portiere",
      preferredFoot: "Destro",
      image: "https://commons.wikimedia.org/wiki/Special:FilePath/Maignan_2_Milan_2022.jpg?width=760",
      imageAlt: "Mike Maignan con il Milan",
    },
    kane: {
      id: "kane",
      teamId: "eng",
      shortName: "Harry Kane",
      fullName: "Harry Edward Kane",
      birthDate: "1993-07-28",
      height: "1,88 m",
      weight: "Dato non disponibile",
      nationality: "Inghilterra",
      club: "FC Bayern Munchen",
      role: "Attaccante",
      preferredFoot: "Destro",
      image: "https://commons.wikimedia.org/wiki/Special:FilePath/Harry_Kane_2018.jpg?width=760",
      imageAlt: "Harry Kane con l'Inghilterra",
    },
    yamal: {
      id: "yamal",
      teamId: "esp",
      shortName: "Lamine Yamal",
      fullName: "Lamine Yamal Nasraoui Ebana",
      birthDate: "2007-07-13",
      height: "1,79 m",
      weight: "72 kg",
      nationality: "Spagna",
      club: "FC Barcelona",
      role: "Ala destra",
      preferredFoot: "Sinistro",
      image: "https://upload.wikimedia.org/wikipedia/commons/e/e3/Lamine_Yamal_in_2025.jpg",
      imageAlt: "Lamine Yamal",
    },
    courtois: {
      id: "courtois",
      teamId: "bel",
      aliases: ["Thibaut Courtois"],
      shortName: "Courtois",
      fullName: "Thibaut Nicolas Marc Courtois",
      birthDate: "1992-05-11",
      height: "2,00 m",
      weight: "96 kg",
      nationality: "Belgio",
      club: "Real Madrid CF",
      role: "Portiere",
      preferredFoot: "Sinistro",
      image: "https://commons.wikimedia.org/wiki/Special:FilePath/Courtois%202018.jpg?width=760",
      imageAlt: "Thibaut Courtois",
    },
    debruyne: {
      id: "debruyne",
      teamId: "bel",
      aliases: ["Kevin De Bruyne"],
      shortName: "De Bruyne",
      fullName: "Kevin De Bruyne",
      birthDate: "1991-06-28",
      height: "1,81 m",
      weight: "Dato non disponibile",
      nationality: "Belgio",
      club: "SSC Napoli",
      role: "Centrocampista",
      preferredFoot: "Destro",
      image: "https://commons.wikimedia.org/wiki/Special:FilePath/Kevin%20De%20Bruyne%20USMNT%20v%20Belgium%20Mar%2028%202026-133.jpg?width=760",
      imageAlt: "Kevin De Bruyne",
    },
    lukaku: {
      id: "lukaku",
      teamId: "bel",
      aliases: ["Romelu Lukaku"],
      shortName: "Lukaku",
      fullName: "Romelu Menama Lukaku Bolingoli",
      birthDate: "1993-05-13",
      height: "1,91 m",
      weight: "Dato non disponibile",
      nationality: "Belgio",
      club: "SSC Napoli",
      role: "Attaccante",
      preferredFoot: "Sinistro",
      image: "https://commons.wikimedia.org/wiki/Special:FilePath/Romelu%20Lukaku%202021.jpg?width=760",
      imageAlt: "Romelu Lukaku",
    },
    vinicius: {
      id: "vinicius",
      teamId: "bra",
      aliases: ["Vinicius Junior", "Vinicius Jr", "Vinicius Júnior", "Vini Jr."],
      shortName: "Vinicius Junior",
      fullName: "Vinicius Paixao de Oliveira Junior",
      birthDate: "2000-07-12",
      height: "1,76 m",
      weight: "73 kg",
      nationality: "Brasile",
      club: "Real Madrid CF",
      role: "Attaccante",
      preferredFoot: "Dato non disponibile",
      image: "",
      imageAlt: "Vinicius Junior",
    },
  },
  teams: [
    { id: "mex", name: "Messico", fifaName: "Mexico", group: "A", flag: "mx", confed: "CONCACAF", rank: 15, titles: 0, host: true, form: 75, style: "Pressing verticale" },
    { id: "rsa", name: "Sudafrica", fifaName: "South Africa", group: "A", flag: "za", confed: "CAF", rank: 60, titles: 0, form: 58, style: "Transizioni" },
    { id: "kor", name: "Corea del Sud", fifaName: "South Korea", group: "A", flag: "kr", confed: "AFC", rank: 25, titles: 0, form: 73, style: "Ritmo e ampiezza" },
    { id: "cze", name: "Cechia", fifaName: "Czech Republic", group: "A", flag: "cz", confed: "UEFA", rank: 41, titles: 0, form: 68, style: "Blocco compatto" },

    { id: "can", name: "Canada", fifaName: "Canada", group: "B", flag: "ca", confed: "CONCACAF", rank: 30, titles: 0, host: true, form: 70, style: "Attacco rapido" },
    { id: "bih", name: "Bosnia-Erzegovina", fifaName: "Bosnia and Herzegovina", group: "B", flag: "ba", confed: "UEFA", rank: 65, titles: 0, form: 61, style: "Qualita centrale" },
    { id: "qat", name: "Qatar", fifaName: "Qatar", group: "B", flag: "qa", confed: "AFC", rank: 55, titles: 0, form: 62, style: "Possesso paziente" },
    { id: "sui", name: "Svizzera", fifaName: "Switzerland", group: "B", flag: "ch", confed: "UEFA", rank: 19, titles: 0, form: 76, style: "Equilibrio" },

    { id: "bra", name: "Brasile", fifaName: "Brazil", group: "C", flag: "br", confed: "CONMEBOL", rank: 6, titles: 5, form: 82, style: "Talento offensivo" },
    { id: "mar", name: "Marocco", fifaName: "Morocco", group: "C", flag: "ma", confed: "CAF", rank: 8, titles: 0, form: 85, style: "Difesa aggressiva" },
    { id: "hai", name: "Haiti", fifaName: "Haiti", group: "C", flag: "ht", confed: "CONCACAF", rank: 83, titles: 0, form: 53, style: "Ripartenze" },
    { id: "sco", name: "Scozia", fifaName: "Scotland", group: "C", flag: "gb-sct", confed: "UEFA", rank: 43, titles: 0, form: 67, style: "Duelli e cross" },

    { id: "usa", name: "Stati Uniti", fifaName: "United States", group: "D", flag: "us", confed: "CONCACAF", rank: 16, titles: 0, host: true, form: 73, style: "Pressing atletico" },
    { id: "par", name: "Paraguay", fifaName: "Paraguay", group: "D", flag: "py", confed: "CONMEBOL", rank: 40, titles: 0, form: 66, style: "Fisicita" },
    { id: "aus", name: "Australia", fifaName: "Australia", group: "D", flag: "au", confed: "AFC", rank: 27, titles: 0, form: 71, style: "Compattezza" },
    { id: "tur", name: "Turchia", fifaName: "Turkey", group: "D", flag: "tr", confed: "UEFA", rank: 22, titles: 0, form: 78, style: "Creativita tra le linee" },

    { id: "ger", name: "Germania", fifaName: "Germany", group: "E", flag: "de", confed: "UEFA", rank: 10, titles: 4, form: 81, style: "Struttura e riaggressione" },
    { id: "cur", name: "Curacao", fifaName: "Curacao", group: "E", flag: "cw", confed: "CONCACAF", rank: 82, titles: 0, form: 54, style: "Blocco medio" },
    { id: "civ", name: "Costa d'Avorio", fifaName: "Cote d'Ivoire", group: "E", flag: "ci", confed: "CAF", rank: 34, titles: 0, form: 74, style: "Potenza sulle fasce" },
    { id: "ecu", name: "Ecuador", fifaName: "Ecuador", group: "E", flag: "ec", confed: "CONMEBOL", rank: 23, titles: 0, form: 75, style: "Pressione e ritmo" },

    { id: "ned", name: "Paesi Bassi", fifaName: "Netherlands", group: "F", flag: "nl", confed: "UEFA", rank: 7, titles: 0, form: 83, style: "Possesso verticale" },
    { id: "jpn", name: "Giappone", fifaName: "Japan", group: "F", flag: "jp", confed: "AFC", rank: 18, titles: 0, form: 77, style: "Tecnica e velocita" },
    { id: "swe", name: "Svezia", fifaName: "Sweden", group: "F", flag: "se", confed: "UEFA", rank: 38, titles: 0, form: 72, style: "Gioco diretto" },
    { id: "tun", name: "Tunisia", fifaName: "Tunisia", group: "F", flag: "tn", confed: "CAF", rank: 44, titles: 0, form: 69, style: "Difesa ordinata" },

    { id: "bel", name: "Belgio", fifaName: "Belgium", group: "G", flag: "be", confed: "UEFA", rank: 9, titles: 0, form: 80, style: "Qualita offensiva" },
    { id: "egy", name: "Egitto", fifaName: "Egypt", group: "G", flag: "eg", confed: "CAF", rank: 29, titles: 0, form: 72, style: "Transizioni" },
    { id: "irn", name: "Iran", fifaName: "Iran", group: "G", flag: "ir", confed: "AFC", rank: 21, titles: 0, form: 75, style: "Blocco e ripartenza" },
    { id: "nzl", name: "Nuova Zelanda", fifaName: "New Zealand", group: "G", flag: "nz", confed: "OFC", rank: 85, titles: 0, form: 55, style: "Fisicita aerea" },

    { id: "esp", name: "Spagna", fifaName: "Spain", group: "H", flag: "es", confed: "UEFA", rank: 2, titles: 1, form: 88, style: "Possesso e controllo" },
    { id: "cpv", name: "Capo Verde", fifaName: "Cape Verde", group: "H", flag: "cv", confed: "CAF", rank: 69, titles: 0, form: 62, style: "Ripartenze larghe" },
    { id: "ksa", name: "Arabia Saudita", fifaName: "Saudi Arabia", group: "H", flag: "sa", confed: "AFC", rank: 61, titles: 0, form: 60, style: "Possesso basso" },
    { id: "uru", name: "Uruguay", fifaName: "Uruguay", group: "H", flag: "uy", confed: "CONMEBOL", rank: 17, titles: 2, form: 78, style: "Intensita e duelli" },

    { id: "fra", name: "Francia", fifaName: "France", group: "I", flag: "fr", confed: "UEFA", rank: 1, titles: 2, form: 92, style: "Attacco profondo" },
    { id: "sen", name: "Senegal", fifaName: "Senegal", group: "I", flag: "sn", confed: "CAF", rank: 14, titles: 0, form: 79, style: "Potenza e transizioni" },
    { id: "irq", name: "Iraq", fifaName: "Iraq", group: "I", flag: "iq", confed: "AFC", rank: 57, titles: 0, form: 63, style: "Compattezza" },
    { id: "nor", name: "Norvegia", fifaName: "Norway", group: "I", flag: "no", confed: "UEFA", rank: 31, titles: 0, form: 74, style: "Finalizzazione" },

    { id: "arg", name: "Argentina", fifaName: "Argentina", group: "J", flag: "ar", confed: "CONMEBOL", rank: 3, titles: 3, form: 88, style: "Controllo e talento" },
    { id: "alg", name: "Algeria", fifaName: "Algeria", group: "J", flag: "dz", confed: "CAF", rank: 28, titles: 0, form: 72, style: "Uno contro uno" },
    { id: "aut", name: "Austria", fifaName: "Austria", group: "J", flag: "at", confed: "UEFA", rank: 24, titles: 0, form: 76, style: "Pressing alto" },
    { id: "jor", name: "Giordania", fifaName: "Jordan", group: "J", flag: "jo", confed: "AFC", rank: 63, titles: 0, form: 61, style: "Ripartenze" },

    { id: "por", name: "Portogallo", fifaName: "Portugal", group: "K", flag: "pt", confed: "UEFA", rank: 5, titles: 0, form: 86, style: "Talento tra le linee" },
    { id: "cod", name: "Congo DR", fifaName: "Congo DR", group: "K", flag: "cd", confed: "CAF", rank: 46, titles: 0, form: 68, style: "Forza fisica" },
    { id: "uzb", name: "Uzbekistan", fifaName: "Uzbekistan", group: "K", flag: "uz", confed: "AFC", rank: 50, titles: 0, form: 66, style: "Ordine tattico" },
    { id: "col", name: "Colombia", fifaName: "Colombia", group: "K", flag: "co", confed: "CONMEBOL", rank: 13, titles: 0, form: 80, style: "Pressing e tecnica" },

    { id: "eng", name: "Inghilterra", fifaName: "England", group: "L", flag: "gb-eng", confed: "UEFA", rank: 4, titles: 1, form: 86, style: "Qualita e profondita" },
    { id: "cro", name: "Croazia", fifaName: "Croatia", group: "L", flag: "hr", confed: "UEFA", rank: 11, titles: 0, form: 78, style: "Controllo a centrocampo" },
    { id: "gha", name: "Ghana", fifaName: "Ghana", group: "L", flag: "gh", confed: "CAF", rank: 74, titles: 0, form: 56, style: "Atletismo" },
    { id: "pan", name: "Panama", fifaName: "Panama", group: "L", flag: "pa", confed: "CONCACAF", rank: 33, titles: 0, form: 70, style: "Blocco compatto" },
  ],
  fixtures: [
    { id: 1, date: "2026-06-11", timeET: "15:00", stage: "Group Stage", group: "A", home: "mex", away: "rsa", venue: "Mexico City Stadium", city: "Mexico City, Mexico" },
    { id: 2, date: "2026-06-11", timeET: "22:00", stage: "Group Stage", group: "A", home: "kor", away: "cze", venue: "Estadio Guadalajara", city: "Guadalajara, Mexico" },
    { id: 3, date: "2026-06-12", timeET: "15:00", stage: "Group Stage", group: "B", home: "can", away: "bih", venue: "Toronto Stadium", city: "Toronto, Canada" },
    { id: 4, date: "2026-06-12", timeET: "21:00", stage: "Group Stage", group: "D", home: "usa", away: "par", venue: "Los Angeles Stadium", city: "Inglewood, USA" },
    { id: 5, date: "2026-06-13", timeET: "15:00", stage: "Group Stage", group: "B", home: "qat", away: "sui", venue: "San Francisco Bay Area Stadium", city: "Santa Clara, USA" },
    { id: 6, date: "2026-06-13", timeET: "18:00", stage: "Group Stage", group: "C", home: "bra", away: "mar", venue: "New York New Jersey Stadium", city: "East Rutherford, USA" },
    { id: 7, date: "2026-06-13", timeET: "21:00", stage: "Group Stage", group: "C", home: "hai", away: "sco", venue: "Boston Stadium", city: "Foxborough, USA" },
    { id: 8, date: "2026-06-14", timeET: "00:00", stage: "Group Stage", group: "D", home: "aus", away: "tur", venue: "BC Place Vancouver", city: "Vancouver, Canada" },
    { id: 9, date: "2026-06-14", timeET: "13:00", stage: "Group Stage", group: "E", home: "ger", away: "cur", venue: "Houston Stadium", city: "Houston, USA" },
    { id: 10, date: "2026-06-14", timeET: "16:00", stage: "Group Stage", group: "F", home: "ned", away: "jpn", venue: "Dallas Stadium", city: "Arlington, USA" },
    { id: 11, date: "2026-06-14", timeET: "19:00", stage: "Group Stage", group: "E", home: "civ", away: "ecu", venue: "Philadelphia Stadium", city: "Philadelphia, USA" },
    { id: 12, date: "2026-06-14", timeET: "22:00", stage: "Group Stage", group: "F", home: "swe", away: "tun", venue: "Estadio Monterrey", city: "Guadalupe, Mexico" },
    { id: 13, date: "2026-06-15", timeET: "12:00", stage: "Group Stage", group: "H", home: "esp", away: "cpv", venue: "Atlanta Stadium", city: "Atlanta, USA" },
    { id: 14, date: "2026-06-15", timeET: "15:00", stage: "Group Stage", group: "G", home: "bel", away: "egy", venue: "Seattle Stadium", city: "Seattle, USA" },
    { id: 15, date: "2026-06-15", timeET: "18:00", stage: "Group Stage", group: "H", home: "ksa", away: "uru", venue: "Miami Stadium", city: "Miami Gardens, USA" },
    { id: 16, date: "2026-06-15", timeET: "21:00", stage: "Group Stage", group: "G", home: "irn", away: "nzl", venue: "Los Angeles Stadium", city: "Inglewood, USA" },
    { id: 17, date: "2026-06-16", timeET: "15:00", stage: "Group Stage", group: "I", home: "fra", away: "sen", venue: "New York New Jersey Stadium", city: "East Rutherford, USA" },
    { id: 18, date: "2026-06-16", timeET: "18:00", stage: "Group Stage", group: "I", home: "irq", away: "nor", venue: "Boston Stadium", city: "Foxborough, USA" },
    { id: 19, date: "2026-06-16", timeET: "21:00", stage: "Group Stage", group: "J", home: "arg", away: "alg", venue: "Kansas City Stadium", city: "Kansas City, USA" },
    { id: 20, date: "2026-06-17", timeET: "00:00", stage: "Group Stage", group: "J", home: "aut", away: "jor", venue: "San Francisco Bay Area Stadium", city: "Santa Clara, USA" },
    { id: 21, date: "2026-06-17", timeET: "13:00", stage: "Group Stage", group: "K", home: "por", away: "cod", venue: "Houston Stadium", city: "Houston, USA" },
    { id: 22, date: "2026-06-17", timeET: "16:00", stage: "Group Stage", group: "L", home: "eng", away: "cro", venue: "Dallas Stadium", city: "Arlington, USA" },
    { id: 23, date: "2026-06-17", timeET: "19:00", stage: "Group Stage", group: "L", home: "gha", away: "pan", venue: "Toronto Stadium", city: "Toronto, Canada" },
    { id: 24, date: "2026-06-17", timeET: "22:00", stage: "Group Stage", group: "K", home: "uzb", away: "col", venue: "Mexico City Stadium", city: "Mexico City, Mexico" },

    { id: 25, date: "2026-06-18", timeET: "12:00", stage: "Group Stage", group: "A", home: "cze", away: "rsa", venue: "Atlanta Stadium", city: "Atlanta, USA" },
    { id: 26, date: "2026-06-18", timeET: "15:00", stage: "Group Stage", group: "B", home: "sui", away: "bih", venue: "Los Angeles Stadium", city: "Inglewood, USA" },
    { id: 27, date: "2026-06-18", timeET: "18:00", stage: "Group Stage", group: "B", home: "can", away: "qat", venue: "BC Place Vancouver", city: "Vancouver, Canada" },
    { id: 28, date: "2026-06-18", timeET: "21:00", stage: "Group Stage", group: "A", home: "mex", away: "kor", venue: "Estadio Guadalajara", city: "Guadalajara, Mexico" },
    { id: 29, date: "2026-06-19", timeET: "15:00", stage: "Group Stage", group: "D", home: "usa", away: "aus", venue: "Seattle Stadium", city: "Seattle, USA" },
    { id: 30, date: "2026-06-19", timeET: "18:00", stage: "Group Stage", group: "C", home: "sco", away: "mar", venue: "Boston Stadium", city: "Foxborough, USA" },
    { id: 31, date: "2026-06-19", timeET: "20:30", stage: "Group Stage", group: "C", home: "bra", away: "hai", venue: "Philadelphia Stadium", city: "Philadelphia, USA" },
    { id: 32, date: "2026-06-19", timeET: "23:00", stage: "Group Stage", group: "D", home: "tur", away: "par", venue: "San Francisco Bay Area Stadium", city: "Santa Clara, USA" },
    { id: 33, date: "2026-06-20", timeET: "13:00", stage: "Group Stage", group: "F", home: "ned", away: "swe", venue: "Houston Stadium", city: "Houston, USA" },
    { id: 34, date: "2026-06-20", timeET: "16:00", stage: "Group Stage", group: "E", home: "ger", away: "civ", venue: "Toronto Stadium", city: "Toronto, Canada" },
    { id: 35, date: "2026-06-20", timeET: "20:00", stage: "Group Stage", group: "E", home: "ecu", away: "cur", venue: "Kansas City Stadium", city: "Kansas City, USA" },
    { id: 36, date: "2026-06-21", timeET: "00:00", stage: "Group Stage", group: "F", home: "tun", away: "jpn", venue: "Estadio Monterrey", city: "Guadalupe, Mexico" },
    { id: 37, date: "2026-06-21", timeET: "12:00", stage: "Group Stage", group: "H", home: "esp", away: "ksa", venue: "Atlanta Stadium", city: "Atlanta, USA" },
    { id: 38, date: "2026-06-21", timeET: "15:00", stage: "Group Stage", group: "G", home: "bel", away: "irn", venue: "Los Angeles Stadium", city: "Inglewood, USA" },
    { id: 39, date: "2026-06-21", timeET: "18:00", stage: "Group Stage", group: "H", home: "uru", away: "cpv", venue: "Miami Stadium", city: "Miami Gardens, USA" },
    { id: 40, date: "2026-06-21", timeET: "21:00", stage: "Group Stage", group: "G", home: "nzl", away: "egy", venue: "BC Place Vancouver", city: "Vancouver, Canada" },
    { id: 41, date: "2026-06-22", timeET: "13:00", stage: "Group Stage", group: "J", home: "arg", away: "aut", venue: "Dallas Stadium", city: "Arlington, USA" },
    { id: 42, date: "2026-06-22", timeET: "17:00", stage: "Group Stage", group: "I", home: "fra", away: "irq", venue: "Philadelphia Stadium", city: "Philadelphia, USA" },
    { id: 43, date: "2026-06-22", timeET: "20:00", stage: "Group Stage", group: "I", home: "nor", away: "sen", venue: "New York New Jersey Stadium", city: "East Rutherford, USA" },
    { id: 44, date: "2026-06-22", timeET: "23:00", stage: "Group Stage", group: "J", home: "jor", away: "alg", venue: "San Francisco Bay Area Stadium", city: "Santa Clara, USA" },
    { id: 45, date: "2026-06-23", timeET: "13:00", stage: "Group Stage", group: "K", home: "por", away: "uzb", venue: "Houston Stadium", city: "Houston, USA" },
    { id: 46, date: "2026-06-23", timeET: "16:00", stage: "Group Stage", group: "L", home: "eng", away: "gha", venue: "Boston Stadium", city: "Foxborough, USA" },
    { id: 47, date: "2026-06-23", timeET: "19:00", stage: "Group Stage", group: "L", home: "pan", away: "cro", venue: "Toronto Stadium", city: "Toronto, Canada" },
    { id: 48, date: "2026-06-23", timeET: "22:00", stage: "Group Stage", group: "K", home: "col", away: "cod", venue: "Estadio Guadalajara", city: "Guadalajara, Mexico" },
    { id: 49, date: "2026-06-24", timeET: "15:00", stage: "Group Stage", group: "B", home: "bih", away: "qat", venue: "Seattle Stadium", city: "Seattle, USA" },
    { id: 50, date: "2026-06-24", timeET: "15:00", stage: "Group Stage", group: "B", home: "sui", away: "can", venue: "BC Place Vancouver", city: "Vancouver, Canada" },
    { id: 51, date: "2026-06-24", timeET: "18:00", stage: "Group Stage", group: "C", home: "mar", away: "hai", venue: "Atlanta Stadium", city: "Atlanta, USA" },
    { id: 52, date: "2026-06-24", timeET: "18:00", stage: "Group Stage", group: "C", home: "sco", away: "bra", venue: "Miami Stadium", city: "Miami Gardens, USA" },
    { id: 53, date: "2026-06-24", timeET: "21:00", stage: "Group Stage", group: "A", home: "cze", away: "mex", venue: "Mexico City Stadium", city: "Mexico City, Mexico" },
    { id: 54, date: "2026-06-24", timeET: "21:00", stage: "Group Stage", group: "A", home: "rsa", away: "kor", venue: "Estadio Monterrey", city: "Guadalupe, Mexico" },
    { id: 55, date: "2026-06-25", timeET: "16:00", stage: "Group Stage", group: "E", home: "cur", away: "civ", venue: "Philadelphia Stadium", city: "Philadelphia, USA" },
    { id: 56, date: "2026-06-25", timeET: "16:00", stage: "Group Stage", group: "E", home: "ecu", away: "ger", venue: "New York New Jersey Stadium", city: "East Rutherford, USA" },
    { id: 57, date: "2026-06-25", timeET: "19:00", stage: "Group Stage", group: "F", home: "jpn", away: "swe", venue: "Dallas Stadium", city: "Arlington, USA" },
    { id: 58, date: "2026-06-25", timeET: "19:00", stage: "Group Stage", group: "F", home: "tun", away: "ned", venue: "Kansas City Stadium", city: "Kansas City, USA" },
    { id: 59, date: "2026-06-25", timeET: "22:00", stage: "Group Stage", group: "D", home: "par", away: "aus", venue: "San Francisco Bay Area Stadium", city: "Santa Clara, USA" },
    { id: 60, date: "2026-06-25", timeET: "22:00", stage: "Group Stage", group: "D", home: "tur", away: "usa", venue: "Los Angeles Stadium", city: "Inglewood, USA" },
    { id: 61, date: "2026-06-26", timeET: "15:00", stage: "Group Stage", group: "I", home: "nor", away: "fra", venue: "Boston Stadium", city: "Foxborough, USA" },
    { id: 62, date: "2026-06-26", timeET: "15:00", stage: "Group Stage", group: "I", home: "sen", away: "irq", venue: "Toronto Stadium", city: "Toronto, Canada" },
    { id: 63, date: "2026-06-26", timeET: "20:00", stage: "Group Stage", group: "H", home: "cpv", away: "ksa", venue: "Houston Stadium", city: "Houston, USA" },
    { id: 64, date: "2026-06-26", timeET: "20:00", stage: "Group Stage", group: "H", home: "uru", away: "esp", venue: "Estadio Guadalajara", city: "Guadalajara, Mexico" },
    { id: 65, date: "2026-06-26", timeET: "23:00", stage: "Group Stage", group: "G", home: "egy", away: "irn", venue: "Seattle Stadium", city: "Seattle, USA" },
    { id: 66, date: "2026-06-26", timeET: "23:00", stage: "Group Stage", group: "G", home: "nzl", away: "bel", venue: "BC Place Vancouver", city: "Vancouver, Canada" },
    { id: 67, date: "2026-06-27", timeET: "17:00", stage: "Group Stage", group: "L", home: "cro", away: "gha", venue: "Philadelphia Stadium", city: "Philadelphia, USA" },
    { id: 68, date: "2026-06-27", timeET: "17:00", stage: "Group Stage", group: "L", home: "pan", away: "eng", venue: "New York New Jersey Stadium", city: "East Rutherford, USA" },
    { id: 69, date: "2026-06-27", timeET: "19:30", stage: "Group Stage", group: "K", home: "col", away: "por", venue: "Miami Stadium", city: "Miami Gardens, USA" },
    { id: 70, date: "2026-06-27", timeET: "19:30", stage: "Group Stage", group: "K", home: "cod", away: "uzb", venue: "Atlanta Stadium", city: "Atlanta, USA" },
    { id: 71, date: "2026-06-27", timeET: "22:00", stage: "Group Stage", group: "J", home: "alg", away: "aut", venue: "Kansas City Stadium", city: "Kansas City, USA" },
    { id: 72, date: "2026-06-27", timeET: "22:00", stage: "Group Stage", group: "J", home: "jor", away: "arg", venue: "Dallas Stadium", city: "Arlington, USA" },

    { id: 73, date: "2026-06-28", timeET: "15:00", stage: "Round of 32", homeLabel: "2A", awayLabel: "2B", venue: "Los Angeles Stadium", city: "Inglewood, USA" },
    { id: 74, date: "2026-06-29", timeET: "16:30", stage: "Round of 32", homeLabel: "1E", awayLabel: "3A/B/C/D/F", venue: "Boston Stadium", city: "Foxborough, USA" },
    { id: 75, date: "2026-06-29", timeET: "21:00", stage: "Round of 32", homeLabel: "1F", awayLabel: "2C", venue: "Estadio Monterrey", city: "Guadalupe, Mexico" },
    { id: 76, date: "2026-06-29", timeET: "13:00", stage: "Round of 32", homeLabel: "1C", awayLabel: "2F", venue: "Houston Stadium", city: "Houston, USA" },
    { id: 77, date: "2026-06-30", timeET: "17:00", stage: "Round of 32", homeLabel: "1I", awayLabel: "3C/D/F/G/H", venue: "New York New Jersey Stadium", city: "East Rutherford, USA" },
    { id: 78, date: "2026-06-30", timeET: "13:00", stage: "Round of 32", homeLabel: "2E", awayLabel: "2I", venue: "Dallas Stadium", city: "Arlington, USA" },
    { id: 79, date: "2026-06-30", timeET: "21:00", stage: "Round of 32", homeLabel: "1A", awayLabel: "3C/E/F/H/I", venue: "Mexico City Stadium", city: "Mexico City, Mexico" },
    { id: 80, date: "2026-07-01", timeET: "12:00", stage: "Round of 32", homeLabel: "1L", awayLabel: "3E/H/I/J/K", venue: "Atlanta Stadium", city: "Atlanta, USA" },
    { id: 81, date: "2026-07-01", timeET: "20:00", stage: "Round of 32", homeLabel: "1D", awayLabel: "3B/E/F/I/J", venue: "San Francisco Bay Area Stadium", city: "Santa Clara, USA" },
    { id: 82, date: "2026-07-01", timeET: "16:00", stage: "Round of 32", homeLabel: "1G", awayLabel: "3A/E/H/I/J", venue: "Seattle Stadium", city: "Seattle, USA" },
    { id: 83, date: "2026-07-02", timeET: "19:00", stage: "Round of 32", homeLabel: "2K", awayLabel: "2L", venue: "Toronto Stadium", city: "Toronto, Canada" },
    { id: 84, date: "2026-07-02", timeET: "15:00", stage: "Round of 32", homeLabel: "1H", awayLabel: "2J", venue: "Los Angeles Stadium", city: "Inglewood, USA" },
    { id: 85, date: "2026-07-02", timeET: "23:00", stage: "Round of 32", homeLabel: "1B", awayLabel: "3E/F/G/I/J", venue: "BC Place Vancouver", city: "Vancouver, Canada" },
    { id: 86, date: "2026-07-03", timeET: "18:00", stage: "Round of 32", homeLabel: "1J", awayLabel: "2H", venue: "Miami Stadium", city: "Miami Gardens, USA" },
    { id: 87, date: "2026-07-03", timeET: "21:30", stage: "Round of 32", homeLabel: "1K", awayLabel: "3D/E/I/J/L", venue: "Kansas City Stadium", city: "Kansas City, USA" },
    { id: 88, date: "2026-07-03", timeET: "14:00", stage: "Round of 32", homeLabel: "2D", awayLabel: "2G", venue: "Dallas Stadium", city: "Arlington, USA" },

    { id: 89, date: "2026-07-04", timeET: "17:00", stage: "Round of 16", homeLabel: "W74", awayLabel: "W77", venue: "Philadelphia Stadium", city: "Philadelphia, USA" },
    { id: 90, date: "2026-07-04", timeET: "13:00", stage: "Round of 16", homeLabel: "W73", awayLabel: "W75", venue: "Houston Stadium", city: "Houston, USA" },
    { id: 91, date: "2026-07-05", timeET: "16:00", stage: "Round of 16", homeLabel: "W76", awayLabel: "W78", venue: "New York New Jersey Stadium", city: "East Rutherford, USA" },
    { id: 92, date: "2026-07-05", timeET: "20:00", stage: "Round of 16", homeLabel: "W79", awayLabel: "W80", venue: "Mexico City Stadium", city: "Mexico City, Mexico" },
    { id: 93, date: "2026-07-06", timeET: "15:00", stage: "Round of 16", homeLabel: "W83", awayLabel: "W84", venue: "Dallas Stadium", city: "Arlington, USA" },
    { id: 94, date: "2026-07-06", timeET: "20:00", stage: "Round of 16", homeLabel: "W81", awayLabel: "W82", venue: "Seattle Stadium", city: "Seattle, USA" },
    { id: 95, date: "2026-07-07", timeET: "12:00", stage: "Round of 16", homeLabel: "W86", awayLabel: "W88", venue: "Atlanta Stadium", city: "Atlanta, USA" },
    { id: 96, date: "2026-07-07", timeET: "16:00", stage: "Round of 16", homeLabel: "W85", awayLabel: "W87", venue: "BC Place Vancouver", city: "Vancouver, Canada" },

    { id: 97, date: "2026-07-09", timeET: "16:00", stage: "Quarter-finals", homeLabel: "W89", awayLabel: "W90", venue: "Boston Stadium", city: "Foxborough, USA" },
    { id: 98, date: "2026-07-10", timeET: "15:00", stage: "Quarter-finals", homeLabel: "W93", awayLabel: "W94", venue: "Los Angeles Stadium", city: "Inglewood, USA" },
    { id: 99, date: "2026-07-11", timeET: "17:00", stage: "Quarter-finals", homeLabel: "W91", awayLabel: "W92", venue: "Miami Stadium", city: "Miami Gardens, USA" },
    { id: 100, date: "2026-07-11", timeET: "21:00", stage: "Quarter-finals", homeLabel: "W95", awayLabel: "W96", venue: "Kansas City Stadium", city: "Kansas City, USA" },
    { id: 101, date: "2026-07-14", timeET: "15:00", stage: "Semi-finals", homeLabel: "W97", awayLabel: "W98", venue: "Dallas Stadium", city: "Arlington, USA" },
    { id: 102, date: "2026-07-15", timeET: "15:00", stage: "Semi-finals", homeLabel: "W99", awayLabel: "W100", venue: "Atlanta Stadium", city: "Atlanta, USA" },
    { id: 103, date: "2026-07-18", timeET: "17:00", stage: "Third place", homeLabel: "L101", awayLabel: "L102", venue: "Miami Stadium", city: "Miami Gardens, USA" },
    { id: 104, date: "2026-07-19", timeET: "15:00", stage: "Final", homeLabel: "W101", awayLabel: "W102", venue: "New York New Jersey Stadium", city: "East Rutherford, USA" },
  ],
  squads: {
    bra: {
      status: "annunciata da FIFA - provvisoria fino al 2 giugno",
      source: "FIFA, 18 maggio 2026",
      url: "https://www.fifa.com/en/tournaments/mens/worldcup/canadamexicousa2026/articles/brazil-squad-announcement-carlo-ancelotti",
      groups: {
        Portieri: ["Alisson", "Ederson", "Weverton"],
        Difensori: ["Alex Sandro", "Bremer", "Danilo", "Douglas Santos", "Gabriel Magalhaes", "Ibanez", "Leo Pereira", "Marquinhos", "Wesley"],
        Centrocampisti: ["Bruno Guimaraes", "Casemiro", "Danilo Santos", "Fabinho", "Lucas Paqueta"],
        Attaccanti: ["Endrick", "Gabriel Martinelli", "Igor Thiago", "Luiz Henrique", "Matheus Cunha", "Neymar Junior", "Raphinha", "Rayan", "Vinicius Junior"],
      },
    },
    sui: {
      status: "annunciata da FIFA - provvisoria fino al 2 giugno",
      source: "FIFA, 20 maggio 2026",
      url: "https://www.fifa.com/en/tournaments/mens/worldcup/canadamexicousa2026/articles/switzerland-squad-announcement-murat-yakin",
      groups: {
        Portieri: ["Gregor Kobel", "Marvin Keller", "Yvon Mvogo"],
        Difensori: ["Manuel Akanji", "Aurele Amenda", "Eray Comert", "Nico Elvedi", "Luca Jaquez", "Miro Muheim", "Ricardo Rodriguez", "Silvan Widmer"],
        Centrocampisti: ["Michel Aebischer", "Christian Fassnacht", "Remo Freuler", "Cedric Itten", "Ardon Jashari", "Fabian Rieder", "Djibril Sow", "Granit Xhaka", "Denis Zakaria"],
        Attaccanti: ["Zeki Amdouni", "Breel Embolo", "Johan Manzambi", "Dan Ndoye", "Noah Okafor", "Ruben Vargas"],
      },
    },
    cur: {
      status: "annunciata da FIFA - provvisoria fino al 2 giugno",
      source: "FIFA, 18 maggio 2026",
      url: "https://www.fifa.com/en/tournaments/mens/worldcup/canadamexicousa2026/articles/curacao-squad-announcement-dick-advocaat",
      groups: {
        Portieri: ["Tyrick Bodack", "Trevor Doornbusch", "Eloy Room"],
        Difensori: ["Riechedly Bazoer", "Joshua Brenet", "Roshon van Eijma", "Sherel Floranus", "Deveron Fonville", "Jurien Gaari", "Armando Obispo", "Shurandy Sambo"],
        Centrocampisti: ["Juninho Bacuna", "Leandro Bacuna", "Livano Comenencia", "Kevin Felida", "Ar'jany Martha", "Tyrese Noslin", "Godfried Roemeratoe"],
        Attaccanti: ["Jeremy Antonisse", "Tahith Chong", "Kenji Gorre", "Sontje Hansen", "Gervane Kastaneer", "Brandley Kuwas", "Jurgen Locadia", "Jearl Margaritha"],
      },
    },
    civ: {
      status: "annunciata da FIFA - provvisoria fino al 2 giugno",
      source: "FIFA, 15 maggio 2026",
      url: "https://www.fifa.com/en/tournaments/mens/worldcup/canadamexicousa2026/articles/cote-divoire-squad-announcement-emerse-fae",
      groups: {
        Portieri: ["Yahia Fofana", "Mohamed Kone", "Alban Lafont"],
        Difensori: ["Emmanuel Agbadou", "Clement Akpa", "Ousmane Diomande", "Guela Doue", "Ghislain Konan", "Odilon Kossounou", "Wilfried Singo", "Evan Ndicka"],
        Centrocampisti: ["Seko Fofana", "Parfait Guiagon", "Christ Inao Oulai", "Franck Kessie", "Ibrahim Sangare", "Jean Michael Seri"],
        Attaccanti: ["Simon Adingra", "Ange-Yoan Bonny", "Amad Diallo", "Oumar Diakite", "Yan Diomande", "Evann Guessand", "Nicolas Pepe", "Bazoumana Toure", "Elye Wahi"],
      },
    },
    swe: {
      status: "annunciata da FIFA - provvisoria fino al 2 giugno",
      source: "FIFA, 11 maggio 2026",
      url: "https://www.fifa.com/en/tournaments/mens/worldcup/canadamexicousa2026/articles/sweden-squad-announcement-world-cup-graham-potter",
      groups: {
        Portieri: ["Viktor Johansson", "Kristoffer Nordfeldt", "Jacob Widell Zetterstrom"],
        Difensori: ["Hjalmar Ekdal", "Gabriel Gudmundsson", "Isak Hien", "Emil Holm", "Gustaf Lagerbielke", "Victor Lindelof", "Erik Smith", "Carl Starfelt", "Elliot Stroud", "Daniel Svensson"],
        Centrocampisti: ["Taha Ali", "Yasin Ayari", "Lucas Bergvall", "Jesper Karlstrom", "Ken Sema", "Mattias Svanberg", "Besfort Zeneli"],
        Attaccanti: ["Alexander Bernhardsson", "Anthony Elanga", "Viktor Gyokeres", "Alexander Isak", "Gustaf Nilsson", "Benjamin Nygren"],
      },
    },
    bel: {
      status: "annunciata da FIFA - provvisoria fino al 2 giugno",
      source: "FIFA, 15 maggio 2026",
      url: "https://www.fifa.com/en/tournaments/mens/worldcup/canadamexicousa2026/articles/belgium-squad-garcia-lukaku-named",
      groups: {
        Portieri: ["Thibaut Courtois", "Senne Lammens", "Mike Penders"],
        Difensori: ["Timothy Castagne", "Zeno Debast", "Maxim De Cuyper", "Koni De Winter", "Brandon Mechele", "Thomas Meunier", "Nathan Ngoy", "Joaquin Seys", "Arthur Theate"],
        Centrocampisti: ["Kevin De Bruyne", "Amadou Onana", "Nicolas Raskin", "Youri Tielemans", "Hans Vanaken", "Axel Witsel"],
        Attaccanti: ["Charles De Ketelaere", "Jeremy Doku", "Matias Fernandez-Pardo", "Romelu Lukaku", "Dodi Lukebakio", "Diego Moreira", "Alexis Saelemaekers", "Leandro Trossard"],
      },
    },
    cpv: {
      status: "annunciata da FIFA - provvisoria fino al 2 giugno",
      source: "FIFA, 18 maggio 2026",
      url: "https://www.fifa.com/en/articles/cabo-verde-squad-announcement-world-cup-bubista",
      groups: {
        Portieri: ["Vozinha", "Marcio Rosa", "CJ dos Santos"],
        Difensori: ["Diney Borges", "Sidny Cabral", "Logan Costa", "Steven Moreira", "Wagner Pina", "Joao Paulo Fernandes", "Roberto 'Pico' Lopes", "Kelvin Pires", "Ianique 'Stopira' Tavares"],
        Centrocampisti: ["Telmo Arcanjo", "Laros Duarte", "Deroy Duarte", "Jamiro Monteiro", "Kevin Pina", "Yannick Semedo"],
        Attaccanti: ["Gilson Benchimol", "Jovane Cabral", "Nuno da Costa", "Dailon Livramento", "Ryan Mendes", "Garry Rodrigues", "Willy Semedo", "Helio Varela"],
      },
    },
    fra: {
      status: "annunciata da FIFA - provvisoria fino al 2 giugno",
      source: "FIFA, 14 maggio 2026",
      url: "https://www.fifa.com/en/tournaments/mens/worldcup/canadamexicousa2026/articles/france-world-cup-squad-named",
      groups: {
        Portieri: ["Mike Maignan", "Robin Risser", "Brice Samba"],
        Difensori: ["Lucas Digne", "Malo Gusto", "Lucas Hernandez", "Theo Hernandez", "Ibrahima Konate", "Jules Kounde", "Maxence Lacroix", "William Saliba", "Dayot Upamecano"],
        Centrocampisti: ["N'Golo Kante", "Manu Kone", "Adrien Rabiot", "Aurelien Tchouameni", "Warren Zaire-Emery"],
        Attaccanti: ["Maghnes Akliouche", "Bradley Barcola", "Rayan Cherki", "Ousmane Dembele", "Desire Doue", "Jean-Philippe Mateta", "Kylian Mbappe", "Michael Olise", "Marcus Thuram"],
      },
    },
    irq: {
      status: "lista preliminare FIFA - 34 giocatori",
      source: "FIFA, 20 maggio 2026",
      url: "https://www.fifa.com/en/tournaments/mens/worldcup/canadamexicousa2026/articles/iraq-preliminary-squad-announcement-graham-arnold",
      groups: {
        Portieri: ["Ahmed Basil", "Jalal Hassan", "Kumel Saadi", "Fahad Talib"],
        Difensori: ["Hussein Ali", "Merchas Doski", "Akam Hashem", "Maytham Jabbar", "Ahmed Maknzi", "Dario Naamo", "Frans Putros", "Mustafa Saadoon", "Rebin Sulaka", "Zaid Tahseen", "Ahmed Yahya", "Manaf Younis"],
        Centrocampisti: ["Hasan Abdulkareem", "Amir Al Ammari", "Youssef Amyn", "Ibrahim Bayesh", "Marko Farji", "Peter Gwargis", "Zidane Iqbal", "Zaid Ismail", "Ali Jassim", "Karar Nabeel", "Jussef Nasrawe", "Ahmed Qasim", "Aimar Sher", "Kevin Yakob"],
        Attaccanti: ["Mohanad Ali", "Aymen Hussein", "Ali Al Hamadi", "Ali Yousef"],
      },
    },
    hai: {
      status: "annunciata da FIFA - provvisoria fino al 2 giugno",
      source: "FIFA, 15 maggio 2026",
      url: "https://www.fifa.com/en/tournaments/mens/worldcup/canadamexicousa2026/articles/haiti-squad-announcement-sebastien-migne",
      groups: {
        Portieri: ["Josue Duverger", "Alexandre Pierre", "Johny Placide"],
        Difensori: ["Ricardo Ade", "Carlens Arcus", "Hannes Delcroix", "Jean-Kevin Duverne", "Martin Experience", "Duke Lacroix", "Wilguens Paugain", "Keeto Thermoncy"],
        Centrocampisti: ["Carl Fred Sainte", "Jean-Ricner Bellegarde", "Leverton Pierre", "Danley Jean Jacques", "Woodensky Pierre", "Dominique Simon"],
        Attaccanti: ["Josue Casimir", "Louicius Deedson", "Derrick Etienne Jr.", "Yassin Fortune", "Wilson Isidor", "Lenny Joseph", "Duckens Nazon", "Frantzdy Pierrot", "Ruben Providence"],
      },
    },
    cod: {
      status: "annunciata da FIFA - provvisoria fino al 2 giugno",
      source: "FIFA, 18 maggio 2026",
      url: "https://www.fifa.com/en/articles/congo-dr-squad-announcement-sebastien-desabre",
      groups: {
        Portieri: ["Lionel Mpasi", "Thimothy Fayulu", "Matthieu Epolo"],
        Difensori: ["Chancel Mbemba", "Aaron Wan-Bissaka", "Alex Tuanzebe", "Arthur Masuaku", "Joris Kayembe", "Steve Kapuadi", "Rocky Bushiri", "Dylan Batubinsika", "Gedeon Kalulu"],
        Centrocampisti: ["Noah Sadiki", "Samuel Moutoussamy", "Edo Kayembe", "Ngal'ayel Mukau", "Charles Pickel", "Nathanael Mbuku", "Brian Cipenga", "Meschack Elia", "Gael Kakuta"],
        Attaccanti: ["Theo Bongonda", "Fiston Mayele", "Cedric Bakambu", "Simon Banza", "Yoane Wissa"],
      },
    },
    aut: {
      status: "annunciata da FIFA - provvisoria fino al 2 giugno",
      source: "FIFA, 18 maggio 2026",
      url: "https://www.fifa.com/en/tournaments/mens/worldcup/canadamexicousa2026/articles/austria-ralf-rangnick-world-cup-squad",
      groups: {
        Portieri: ["Patrick Pentz", "Alexander Schlager", "Florian Wiegele"],
        Difensori: ["David Affengruber", "David Alaba", "Kevin Danso", "Marco Friedl", "Philipp Lienhart", "Phillipp Mwene", "Stefan Posch", "Alexander Prass", "Michael Svoboda"],
        Centrocampisti: ["Christoph Baumgartner", "Carney Chukwuemeka", "Florian Grillitsch", "Konrad Laimer", "Marcel Sabitzer", "Xaver Schlager", "Romano Schmid", "Alessandro Schopf", "Nicolas Seiwald", "Paul Wanner", "Patrick Wimmer"],
        Attaccanti: ["Marko Arnautovic", "Michael Gregoritsch", "Sasa Kalajdzic"],
      },
    },
    por: {
      status: "27 convocati FIFA - da ridurre a 26 entro il 2 giugno",
      source: "FIFA, 19 maggio 2026",
      url: "https://www.fifa.com/en/tournaments/mens/worldcup/canadamexicousa2026/articles/cristiano-ronaldo-roberto-martinez-portugal-squad-announcement",
      groups: {
        Portieri: ["Diogo Costa", "Jose Sa", "Rui Silva", "Ricardo Velho"],
        Difensori: ["Tomas Araujo", "Joao Cancelo", "Diogo Dalot", "Ruben Dias", "Goncalo Inacio", "Nuno Mendes", "Matheus Nunes", "Nelson Semedo", "Renato Veiga"],
        Centrocampisti: ["Samuel Costa", "Bruno Fernandes", "Joao Neves", "Ruben Neves", "Bernardo Silva", "Vitinha"],
        Attaccanti: ["Francisco Conceicao", "Joao Felix", "Goncalo Guedes", "Rafael Leao", "Pedro Neto", "Goncalo Ramos", "Cristiano Ronaldo", "Francisco Trincao"],
      },
    },
  },
};
